### ISSUE TITLE
Number of commands needed to retrieve serial number 

### ISSUE THREAD

**Issue by novvere** [MyElectrons/sfm3300-arduino#1]
I'm writing an Arduino library to use this sensor in an open source ventilator project. I have seen You just use 1 command 0x31AE to get serial number as indicated in the sensor I2C functional description document but there is another document indicating  a second command (0x31AF) is needed.

As we still don't have the sensor , do you know the reason for this difference?

**Comment by MyElectrons** [comment]
Hi Miguel,
I am terribly sorry for the late response!
I followed the app note from Sensirion. Please check it here: https://www.sensirion.com/en/download-center/mass-flow-meters/proximal-flow-sensors-sfm3300-autoclavable-washable-or-single-use/
and download "Application Note SFM3xxx I2C Functional Description" - that's the document describing what worked for me.
